language: java

jdk:
  - openjdk8

dist: xenial

addons:
  homebrew:
    packages:
      - kotlin
    update: true

stages:
  - build
  - test
  - name: release
    if: tag IS present

install:
  - source <(curl -s "https://get.sdkman.io")
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install kotlin
  - curl -LO https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh && chmod +x assert.sh
  - export PATH="$(pwd):$PATH"

# https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - name: Assemble artifacts
      stage: build
      script: ./gradlew assemble
      install: skip
    - name: Internal API tests
      stage: test
      script: ./gradlew check
      install: skip
    - name: Integration tests
      stage: test
      script:
        - export KSCRIPT_HOME=${TRAVIS_BUILD_DIR}

        # Install kscript dist and populate PATH with it
        - ./gradlew installDist
        - export PATH="${KSCRIPT_HOME}/build/install/kscript/bin:$PATH"

        # Required tools here?
        - which kscript
        - which assert.sh

        ## does it run outside of test-suite?
        - kscript --help
        - java -version

        ## create mock `idea` to allow for idea environment bootstrapping tests (see kscript_nocall)
        - touch idea && chmod +x idea

        - kscript 'println("kotlin rocks")'

        - test/test_suite.sh
